/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as PartyIdIndexImport } from "./routes/$partyId/index";
import { Route as ServerServerIdImport } from "./routes/server/$serverId";

// Create/Update Routes

const IndexRoute = IndexImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => rootRoute,
} as any);

const PartyIdIndexRoute = PartyIdIndexImport.update({
    id: "/$partyId/",
    path: "/$partyId/",
    getParentRoute: () => rootRoute,
} as any);

const ServerServerIdRoute = ServerServerIdImport.update({
    id: "/server/$serverId",
    path: "/server/$serverId",
    getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/": {
            id: "/";
            path: "/";
            fullPath: "/";
            preLoaderRoute: typeof IndexImport;
            parentRoute: typeof rootRoute;
        };
        "/server/$serverId": {
            id: "/server/$serverId";
            path: "/server/$serverId";
            fullPath: "/server/$serverId";
            preLoaderRoute: typeof ServerServerIdImport;
            parentRoute: typeof rootRoute;
        };
        "/$partyId/": {
            id: "/$partyId/";
            path: "/$partyId";
            fullPath: "/$partyId";
            preLoaderRoute: typeof PartyIdIndexImport;
            parentRoute: typeof rootRoute;
        };
    }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
    "/": typeof IndexRoute;
    "/server/$serverId": typeof ServerServerIdRoute;
    "/$partyId": typeof PartyIdIndexRoute;
}

export interface FileRoutesByTo {
    "/": typeof IndexRoute;
    "/server/$serverId": typeof ServerServerIdRoute;
    "/$partyId": typeof PartyIdIndexRoute;
}

export interface FileRoutesById {
    __root__: typeof rootRoute;
    "/": typeof IndexRoute;
    "/server/$serverId": typeof ServerServerIdRoute;
    "/$partyId/": typeof PartyIdIndexRoute;
}

export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths: "/" | "/server/$serverId" | "/$partyId";
    fileRoutesByTo: FileRoutesByTo;
    to: "/" | "/server/$serverId" | "/$partyId";
    id: "__root__" | "/" | "/server/$serverId" | "/$partyId/";
    fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    ServerServerIdRoute: typeof ServerServerIdRoute;
    PartyIdIndexRoute: typeof PartyIdIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    ServerServerIdRoute: ServerServerIdRoute,
    PartyIdIndexRoute: PartyIdIndexRoute,
};

export const routeTree = rootRoute
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/server/$serverId",
        "/$partyId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/server/$serverId": {
      "filePath": "server/$serverId.tsx"
    },
    "/$partyId/": {
      "filePath": "$partyId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
